import re
import logging
import copy
import json
import random
from pathlib import Path
import cma_agent.engine as engine
import cma_agent.adaptive as adaptive
import cma_agent.skills as skills
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from typing import Optional

_original_db = engine.db
_schema_ready = False


def db():
    global _schema_ready
    if not engine.DATABASE_URL:
        return _original_db()
    c = engine._PostgresConnection()
    if not _schema_ready:
        c.execute("CREATE TABLE IF NOT EXISTS attempts(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,ts TEXT,question_id TEXT,part TEXT,domain TEXT,difficulty TEXT,selected TEXT,correct INTEGER,confidence INTEGER,session_id TEXT)")
        c.execute("CREATE TABLE IF NOT EXISTS goals(id INTEGER PRIMARY KEY CHECK(id=1),target_date TEXT,part TEXT,daily_minutes INTEGER)")
        c.execute("CREATE TABLE IF NOT EXISTS study_plans(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,created_at TEXT,target_date TEXT,part TEXT,daily_minutes INTEGER)")
        c.execute("CREATE TABLE IF NOT EXISTS preferences(id INTEGER PRIMARY KEY CHECK(id=1),part TEXT,difficulty TEXT,domain TEXT,resume_question_id TEXT)")
        c.execute("CREATE TABLE IF NOT EXISTS session_state(id INTEGER PRIMARY KEY CHECK(id=1),session_id TEXT,last_activity TEXT)")
        c.execute("ALTER TABLE attempts ADD COLUMN IF NOT EXISTS session_id TEXT")
        c.execute("ALTER TABLE preferences ADD COLUMN IF NOT EXISTS resume_question_id TEXT")
        c.execute("CREATE INDEX IF NOT EXISTS idx_attempts_question ON attempts(question_id)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_attempts_domain ON attempts(domain)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_attempts_session ON attempts(session_id)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_attempts_ts ON attempts(ts)")
        c.execute("ALTER TABLE attempts ADD COLUMN IF NOT EXISTS bank_revision TEXT")
        c.commit()
        _schema_ready = True
    return c


engine.db = db
_data_dir = Path(__file__).resolve().parent / "data"
_case_bank = []
try:
    _cases = json.loads((_data_dir / "cases.json").read_text(encoding="utf-8"))
    for _case in _cases:
        for _idx, _item in enumerate(_case.get("questions", []), 1):
            _case_q = {
                "id": f"{_case['id']}-Q{_idx}",
                "part": _case["part"],
                "domain": _case["domain"],
                "difficulty": _case.get("difficulty", "Medium"),
                "question": _item["q"],
                "choices": _item["choices"],
                "answer": _item["answer"],
                "explanation": _item.get("explanation", ""),
                "calculation": _item.get("calculation"),
                "numeric_check": _item.get("numeric_check"),
                "skills": _item["skills"],
                "content_revision": _case["content_revision"],
                "is_case": True,
                "case_id": _case["id"],
                "case_title": _case.get("title", "Case Practice"),
                "scenario": _case.get("scenario", ""),
                "case_question_number": _idx,
                "case_question_count": len(_case.get("questions", [])),
            }
            engine.QUESTIONS.append(_case_q)
            _case_bank.append(_case_q)
except Exception:
    _cases = []

from cma_agent.engine import (
    choose_question, choose_followup, grade, learning_feedback,
    learning_snapshot, stats, plan, save_goal, get_preferences,
    save_preferences, save_resume_question, clear_resume_question,
    get_question, goal, goal_history, get_or_start_session,
    start_new_session, session_stats,
)

app = FastAPI(title="CMA Coach API")


class Settings(BaseModel):
    part: str = "Both"
    difficulty: str = "All"
    domain: str = "All"


class GradeRequest(BaseModel):
    question_id: str
    selected: str
    confidence: int = 0
    session_id: Optional[str] = None


class QuestionRequest(BaseModel):
    part: str = "Both"
    domain: str = "All"
    difficulty: str = "All"
    exclude: list[str] = []


class FollowupRequest(BaseModel):
    question_id: str
    selected: str
    part: str = "Both"
    difficulty: str = "All"


class GoalRequest(BaseModel):
    target_date: str
    part: str
    daily_minutes: int


class CaseRequest(BaseModel):
    part: str = "Both"
    domain: str = "All"
    exclude_case_ids: list[str] = []


class ExamStartRequest(BaseModel):
    part: str = "Part 1"


class ExamGradeRequest(BaseModel):
    question_id: str
    selected: str
    confidence: int = 0
    session_id: Optional[str] = None


_CONTEXT_TAILS = (
    " for a manufacturing business.",
    " when evaluating a current-period decision.",
    " when comparing two operating alternatives.",
    " in a multi-site organization.",
    " for a manager preparing a forecast.",
    " when analyzing the current reporting period.",
    " when reviewing the underlying business drivers.",
    " for a monthly management review.",
)


def clean_question(q):
    if not q:
        return q
    result = copy.deepcopy(q)
    result.pop("numeric_check", None)
    result.pop("content_revision", None)
    text = result.get("question")
    if isinstance(text, str):
        for tail in _CONTEXT_TAILS:
            if text.endswith(tail):
                result["question"] = text[:-len(tail)].rstrip()
                break
    return result


def _public_exam_question(q):
    result = clean_question(q)
    for key in ("answer", "explanation", "calculation"):
        result.pop(key, None)
    return result


def _recent_question_ids(limit=15):
    c = db()
    rows = c.execute("SELECT question_id FROM attempts ORDER BY id DESC LIMIT ?", (limit,)).fetchall()
    ids = [r["question_id"] for r in rows]
    c.close()
    return ids


def _choose_case(part="Both", domain="All", exclude_case_ids=None):
    excluded = set(exclude_case_ids or [])
    eligible = [c for c in _cases if c.get("id") not in excluded
                and (part == "Both" or c.get("part") == part)
                and (domain == "All" or c.get("domain") == domain)]
    if not eligible:
        eligible = [c for c in _cases if (part == "Both" or c.get("part") == part)
                    and (domain == "All" or c.get("domain") == domain)]
    return random.choice(eligible) if eligible else None


def _public_case(case):
    result = copy.deepcopy(case)
    public_questions = []
    for idx, item in enumerate(case.get("questions", []), 1):
        public_questions.append({
            "id": f"{case['id']}-Q{idx}",
            "question": item.get("q", ""),
            "choices": item.get("choices", {}),
            "question_number": idx,
            "question_count": len(case.get("questions", [])),
        })
    result["questions"] = public_questions
    return result


_BLUEPRINT = {
    "Part 1": {
        "External Financial Reporting Decisions": 15,
        "Planning, Budgeting, and Forecasting": 20,
        "Performance Management": 20,
        "Cost Management": 15,
        "Internal Controls": 15,
        "Technology and Analytics": 15,
    },
    "Part 2": {
        "Financial Statement Analysis": 20,
        "Corporate Finance": 20,
        "Business Decision Analysis": 25,
        "Enterprise Risk Management": 10,
        "Capital Investment Decisions": 10,
        "Professional Ethics": 15,
    },
}


def _exam_questions(part):
    weights = _BLUEPRINT.get(part)
    if not weights:
        raise HTTPException(status_code=400, detail="Exam simulation requires Part 1 or Part 2")
    regular = [q for q in engine.QUESTIONS if q.get("part") == part and not q.get("is_case")]
    selected = []
    shortages = [(domain, len([q for q in regular if q["domain"] == domain]), count)
                 for domain, count in weights.items()
                 if len([q for q in regular if q["domain"] == domain]) < count]
    if shortages:
        details = "; ".join(f"{d}: {n} reviewed questions, {needed} required" for d, n, needed in shortages)
        raise HTTPException(status_code=400, detail=(
            "A 100-question set with the CMA domain proportions is not yet available. "
            + details + ". Use mixed practice while these gaps are addressed."
        ))
    for domain, count in weights.items():
        pool = [q for q in regular if q["domain"] == domain]
        selected.extend(random.sample(pool, count))
    random.shuffle(selected)
    return selected


@app.get("/api/health")
def health():
    return {"ok": True}


@app.get("/api/session")
def session():
    sid = get_or_start_session()
    return {"session_id": sid, "stats": session_stats(sid)}


@app.post("/api/session/new")
def new_session():
    sid = start_new_session()
    return {"session_id": sid, "stats": session_stats(sid)}


@app.get("/api/preferences")
def preferences():
    return get_preferences()


@app.post("/api/preferences")
def preferences_save(settings: Settings):
    clear_resume_question()
    save_preferences(settings.part, settings.difficulty, settings.domain)
    return get_preferences()


@app.get("/api/question/{question_id}")
def question(question_id: str):
    q = get_question(question_id)
    if not q:
        raise HTTPException(status_code=404, detail="Question not found")
    return clean_question(q)


@app.post("/api/question")
def question_choose(request: QuestionRequest):
    exclude = list(dict.fromkeys((request.exclude or []) + _recent_question_ids(15)))
    q = skills.choose_question(request.part, request.domain, request.difficulty, exclude=exclude)
    save_resume_question(q["id"])
    return clean_question(q)


@app.post("/api/followup")
def followup(request: FollowupRequest):
    q = adaptive.choose_followup(request.question_id, request.selected, request.part, request.difficulty)
    if q is None:
        return {"drill_complete": True}
    save_resume_question(q["id"])
    return clean_question(q)


@app.post("/api/grade")
def grade_question(request: GradeRequest):
    q = get_question(request.question_id)
    if not q:
        raise HTTPException(status_code=404, detail="Question not found")
    try:
        ok, graded = grade(request.question_id, request.selected, request.confidence, request.session_id)
        adaptive.record_result(request.question_id, ok, request.confidence)
        feedback = learning_feedback(request.question_id, request.selected, request.confidence)
        skill_feedback = skills.record_attempt(q, ok, request.confidence)
        feedback["skills"] = skill_feedback["skills"]
        feedback["mistake_type"] = skill_feedback["mistake_type"]
        feedback["coaching"] = skill_feedback["coaching"]
        sid = request.session_id or get_or_start_session()
        return {"correct": bool(ok), "question": clean_question(graded), "feedback": feedback, "session": session_stats(sid)}
    except Exception:
        logging.getLogger(__name__).exception("CMA grade failed for question %s", request.question_id)
        raise


@app.post("/api/case")
def case_choose(request: CaseRequest):
    case = _choose_case(request.part, request.domain, request.exclude_case_ids)
    if not case:
        raise HTTPException(status_code=404, detail="No case found for those settings")
    return _public_case(case)


@app.post("/api/exam/start")
def exam_start(request: ExamStartRequest):
    questions = _exam_questions(request.part)
    cases = [c for c in _cases if c.get("part") == request.part]
    if len(cases) > 2:
        cases = random.sample(cases, 2)
    return {
        "part": request.part,
        "mcq_count": len(questions),
        "mcq_time_minutes": 180,
        "case_time_minutes": 60,
        "format_note": "Timed MCQ practice with short case exercises, not a complete replica of the CMA case section.",
        "mcq_questions": [_public_exam_question(q) for q in questions],
        "cases": [_public_case(c) for c in cases],
        "blueprint": _BLUEPRINT[request.part],
    }


@app.post("/api/exam/grade")
def exam_grade(request: ExamGradeRequest):
    q = get_question(request.question_id)
    if not q:
        raise HTTPException(status_code=404, detail="Question not found")
    ok, _graded = grade(request.question_id, request.selected, request.confidence, request.session_id)
    # Exam answers are recorded in history but deliberately do not enter the
    # spaced-review scheduler because the simulation has no confidence input.
    return {"correct": bool(ok)}


@app.get("/api/summary")
def summary():
    """Lightweight real-data summary for the practice UI hero."""
    c = db()
    row = c.execute("SELECT COUNT(*) AS attempted, COALESCE(SUM(correct),0) AS correct FROM attempts").fetchone()
    focus = c.execute("""
        SELECT domain, COUNT(*) AS n, COALESCE(SUM(correct),0) AS correct
        FROM attempts
        GROUP BY domain
        ORDER BY n DESC, domain ASC
        LIMIT 1
    """).fetchone()
    c.close()
    attempted = int(row["attempted"] or 0)
    correct = int(row["correct"] or 0)
    accuracy = round(correct / attempted * 100, 1) if attempted else 0
    regular_bank = [q for q in engine.QUESTIONS if not q.get("is_case")]
    return {
        "attempted": attempted,
        "accuracy": accuracy,
        "focus_domain": focus["domain"] if focus else "Build coverage",
        "question_bank_size": len(regular_bank),
    }


@app.get("/api/dashboard")
def dashboard():
    return {"stats": stats(), "snapshot": learning_snapshot(), "adaptive": adaptive.snapshot(), "skills": skills.snapshot()}


@app.get("/api/study-plan")
def study_plan():
    return {"goal": goal(), "plan": plan(), "history": goal_history()}


@app.post("/api/study-plan")
def study_plan_save(request: GoalRequest):
    save_goal(request.target_date, request.part, request.daily_minutes)
    return {"goal": goal(), "plan": plan(), "history": goal_history()}


@app.get("/api/study-profile")
def study_profile():
    s = stats()
    snap = learning_snapshot()
    g = goal()
    return {
        "profile_version": "1.0",
        "overall": {
            "questions_completed": s["attempted"],
            "accuracy": s["accuracy"],
            "question_bank_size": s["question_bank_size"],
        },
        "current_plan": g,
        "priority_topics": {
            "weak_domains": snap["weak_domains"],
            "fragile_domains": snap["fragile_domains"],
            "recent_misses": snap["recent_misses"],
        },
        "study_mode_guidance": [
            "Teach weak topics before drilling them.",
            "Use one question at a time.",
            "Guide reasoning before revealing an answer when appropriate.",
            "Reinforce low-confidence correct answers.",
            "Use follow-up questions after misses.",
        ],
    }


app.mount("/", StaticFiles(directory="frontend/dist", html=True), name="frontend")
