"""Skill-level CMA learning engine.

CMA Coach is practice-first: each attempt is mapped to a named CMA skill,
classified by the kind of miss/confidence signal, and used to choose future
questions.  This deliberately supplements the domain scheduler rather than
replacing spaced retrieval.
"""
from __future__ import annotations

import random
import cma_agent.engine as engine
import cma_agent.adaptive as adaptive


def _labels(q):
    fn = getattr(adaptive, "skill_labels_for_question", None)
    labels = fn(q) if fn else []
    return labels or [q.get("domain", "General CMA skill")]


def _ensure_schema(conn):
    if engine.DATABASE_URL:
        conn.execute("""CREATE TABLE IF NOT EXISTS skill_attempts(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question_id TEXT, part TEXT, domain TEXT, skill TEXT,
            correct INTEGER, confidence INTEGER, mistake_type TEXT, ts TEXT)""")
    else:
        conn.execute("""CREATE TABLE IF NOT EXISTS skill_attempts(
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            question_id TEXT, part TEXT, domain TEXT, skill TEXT,
            correct INTEGER, confidence INTEGER, mistake_type TEXT, ts TEXT)""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_skill_attempts_skill ON skill_attempts(skill)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_skill_attempts_domain ON skill_attempts(domain)")
    conn.commit()


def diagnose(q, correct, confidence):
    confidence = int(confidence or 0)
    if correct and confidence <= 1:
        return "confidence_gap", "You got it right, but not confidently. Prove it once more without relying on recognition."
    if correct:
        return "solid", "You applied this skill correctly. The coach can space it out and spend more time elsewhere."
    if q.get("calculation"):
        if confidence >= 3:
            return "calculation_application_gap", "You were confident but the calculation/application missed. Rebuild the setup before touching the numbers."
        return "calculation_gap", "Rebuild the formula and setup, then solve a fresh version immediately."
    if confidence >= 3:
        return "concept_application_gap", "You were confident but applied the rule incorrectly. Contrast the rule with the distractor you chose."
    return "knowledge_gap", "You were unsure and missed it. Use the short explanation, then immediately apply the same skill again."


def record_attempt(q, correct, confidence):
    mistake_type, coaching = diagnose(q, bool(correct), confidence)
    conn = engine.db()
    _ensure_schema(conn)
    from datetime import datetime
    ts = datetime.now().isoformat(timespec="seconds")
    for skill in _labels(q):
        conn.execute(
            "INSERT INTO skill_attempts(question_id,part,domain,skill,correct,confidence,mistake_type,ts) VALUES(?,?,?,?,?,?,?,?)",
            (q["id"], q["part"], q["domain"], skill, int(bool(correct)), int(confidence or 0), mistake_type, ts),
        )
    conn.commit()
    conn.close()
    return {"skills": _labels(q), "mistake_type": mistake_type, "coaching": coaching}


def snapshot(part="Both", domain="All"):
    conn = engine.db()
    _ensure_schema(conn)
    where, args = [], []
    if part != "Both":
        where.append("part=?"); args.append(part)
    if domain != "All":
        where.append("domain=?"); args.append(domain)
    clause = (" WHERE " + " AND ".join(where)) if where else ""
    rows = conn.execute(
        f"""SELECT skill,domain,COUNT(*) attempts,COALESCE(SUM(correct),0) correct,
        COALESCE(AVG(confidence),0) avg_confidence
        FROM skill_attempts{clause} GROUP BY skill,domain""", tuple(args)
    ).fetchall()
    conn.close()
    items = []
    for r in rows:
        attempts = int(r["attempts"] or 0)
        correct = int(r["correct"] or 0)
        accuracy = round(correct / attempts * 100, 1) if attempts else 0
        avg_conf = round(float(r["avg_confidence"] or 0), 1)
        # Accuracy is primary; low confidence keeps a correct skill in rotation.
        priority = (100 - accuracy) + max(0, 2.2 - avg_conf) * 12 + max(0, 4 - attempts) * 3
        status = "Needs work" if accuracy < 70 else "Reinforce" if accuracy < 85 or avg_conf < 2 else "Strong"
        items.append({
            "skill": r["skill"], "domain": r["domain"], "attempts": attempts,
            "accuracy": accuracy, "avg_confidence": avg_conf,
            "status": status, "priority": round(priority, 1),
        })
    items.sort(key=lambda x: (-x["priority"], x["attempts"], x["skill"]))
    return {"priorities": items[:8], "skills_tracked": len(items)}


def choose_question(part="Both", domain="All", difficulty="All", exclude=None):
    # Ask the spaced scheduler first. If it selected a question that is
    # actually due, preserve that retrieval instead of overriding it.
    due = adaptive.choose_question(part, domain, difficulty, exclude=exclude)
    conn = engine.db()
    adaptive.ensure_schema(conn)
    from datetime import datetime
    due_row = conn.execute("SELECT question_id FROM review_state WHERE question_id=? AND due_at<=?", (due["id"], datetime.now().isoformat(timespec="seconds"))).fetchone()
    conn.close()
    if due_row:
        return due
    snap = snapshot(part, domain)
    priorities = [x for x in snap["priorities"] if x["status"] != "Strong"]
    if not priorities:
        return due

    target = priorities[0]["skill"]
    candidates = []
    excluded = set(exclude or [])
    for q in engine.QUESTIONS:
        if q.get("is_case") or q.get("id") in excluded:
            continue
        if part != "Both" and q.get("part") != part:
            continue
        if domain != "All" and q.get("domain") != domain:
            continue
        if difficulty != "All" and q.get("difficulty") != difficulty:
            continue
        if target in _labels(q):
            candidates.append(q)
    if not candidates:
        return due

    conn = engine.db()
    attempted = {r["question_id"] for r in conn.execute("SELECT question_id FROM attempts").fetchall()}
    conn.close()
    unseen = [q for q in candidates if q["id"] not in attempted]
    return random.choice(unseen or candidates)
