import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const p1=['External Financial Reporting Decisions','Planning, Budgeting, and Forecasting','Performance Management','Cost Management','Internal Controls','Technology and Analytics'];
const p2=['Financial Statement Analysis','Corporate Finance','Business Decision Analysis','Enterprise Risk Management','Capital Investment Decisions','Professional Ethics'];
const PREF_KEY='cma-coach-preferences-v2';
const QUESTION_KEY='cma-coach-current-question-v2';
const api=(path,opts={})=>fetch(path,{headers:{'Content-Type':'application/json'},...opts}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.detail||'Request failed');return d});
const readLocal=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const writeLocal=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};

function App(){
 const [prefs,setPrefs]=useState(()=>readLocal(PREF_KEY,{part:'Both',difficulty:'All',domain:'All'})),[q,setQ]=useState(()=>readLocal(QUESTION_KEY,null)),[answer,setAnswer]=useState(''),[confidence,setConfidence]=useState(0),[review,setReview]=useState(null),[session,setSession]=useState({attempted:0,accuracy:0}),[tab,setTab]=useState('Practice'),[dashboard,setDashboard]=useState(null),[study,setStudy]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[drillCount,setDrillCount]=useState(0),[caseData,setCaseData]=useState(null),[caseIndex,setCaseIndex]=useState(0),[caseReview,setCaseReview]=useState(null),[exam,setExam]=useState(null),[examPhase,setExamPhase]=useState('mcq'),[examIndex,setExamIndex]=useState(0),[examCaseIndex,setExamCaseIndex]=useState(0),[examCaseQIndex,setExamCaseQIndex]=useState(0),[examCorrect,setExamCorrect]=useState(0),[examMcqCorrect,setExamMcqCorrect]=useState(0),[examTotal,setExamTotal]=useState(100),[examStartedAt,setExamStartedAt]=useState(null),[examSecondsLeft,setExamSecondsLeft]=useState(0);
 useEffect(()=>{Promise.all([api('/api/preferences'),api('/api/session')]).then(([p,s])=>{const local=readLocal(PREF_KEY,p);setPrefs(local);writeLocal(PREF_KEY,{part:local.part,difficulty:local.difficulty,domain:local.domain});setSession(s.stats);const resume=p.resume_question_id;if(resume)api('/api/question/'+resume).then(x=>{setQ(x);writeLocal(QUESTION_KEY,x)}).catch(()=>{});}).catch(()=>{const local=readLocal(PREF_KEY,{part:'Both',difficulty:'All',domain:'All'});setPrefs(local);const localQ=readLocal(QUESTION_KEY,null);if(localQ)setQ(localQ)});},[]);
 useEffect(()=>{if(!examStartedAt||examPhase==='done')return;const timer=setInterval(()=>{const duration=examPhase==='mcq'?180*60:60*60;const left=Math.max(0,examStartedAt+duration-Math.floor(Date.now()/1000));setExamSecondsLeft(left);if(left===0){if(examPhase==='mcq'){if(examMcqCorrect>=50&&exam?.cases?.length){setExamPhase('cases');setExamCaseIndex(0);setExamCaseQIndex(0);setExamStartedAt(Math.floor(Date.now()/1000));}else{setExamPhase('done')}}else{setExamPhase('done')}}},1000);return()=>clearInterval(timer)},[examStartedAt,examPhase,examMcqCorrect,exam]);
 const domains=prefs.part==='Part 1'?p1:prefs.part==='Part 2'?p2:[...p1,...p2];
 async function choose(){setBusy(true);setError('');try{const x=await api('/api/question',{method:'POST',body:JSON.stringify(prefs)});setQ(x);writeLocal(QUESTION_KEY,x);setReview(null);setAnswer('');setConfidence(0);setDrillCount(0)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function submit(){if(!answer||!confidence)return;setBusy(true);try{const r=await api('/api/grade',{method:'POST',body:JSON.stringify({question_id:q.id,selected:answer,confidence})});setReview(r);setSession(r.session);setDashboard(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function next(follow=false){setBusy(true);setError('');try{const r=await api(follow?'/api/followup':'/api/question',{method:'POST',body:JSON.stringify(follow?{question_id:q.id,selected:answer,part:prefs.part,difficulty:prefs.difficulty}:{...prefs,exclude:[q.id]})});if(follow&&r.drill_complete){setDrillCount(3);return}setQ(r);writeLocal(QUESTION_KEY,r);setReview(null);setAnswer('');setConfidence(0);setDrillCount(follow?drillCount+1:0)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function startDueReview(){setBusy(true);setError('');try{const x=await api('/api/question',{method:'POST',body:JSON.stringify({...prefs,exclude:[]})});setQ(x);writeLocal(QUESTION_KEY,x);setReview(null);setAnswer('');setConfidence(0);setDrillCount(0);setTab('Practice')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function startCase(){setBusy(true);setError('');try{const c=await api('/api/case',{method:'POST',body:JSON.stringify({part:prefs.part,domain:prefs.domain})});setCaseData(c);setCaseIndex(0);setCaseReview(null);setAnswer('');setConfidence(0)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function submitCase(){const cq=caseData?.questions?.[caseIndex];if(!cq||!answer)return;setBusy(true);setError('');try{const r=await api('/api/grade',{method:'POST',body:JSON.stringify({question_id:cq.id,selected:answer,confidence:confidence||2})});setCaseReview(r);setSession(r.session);setDashboard(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 function nextCase(){if(caseIndex+1<(caseData?.questions?.length||0)){setCaseIndex(caseIndex+1);setCaseReview(null);setAnswer('');setConfidence(0)}else{startCase()}}
 async function startExam(){setBusy(true);setError('');try{const part=prefs.part==='Part 2'?'Part 2':'Part 1';const x=await api('/api/exam/start',{method:'POST',body:JSON.stringify({part})});setExam(x);setExamPhase('mcq');setExamIndex(0);setExamCaseIndex(0);setExamCaseQIndex(0);setExamCorrect(0);setExamMcqCorrect(0);setExamTotal(x.mcq_count);setExamStartedAt(Math.floor(Date.now()/1000));setExamSecondsLeft(180*60);setAnswer('');setTab('Exam Simulation')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const currentExamQuestion=exam?.mcq_questions?.[examIndex];
 const currentExamCase=exam?.cases?.[examCaseIndex];
 const currentExamCaseQuestion=currentExamCase?.questions?.[examCaseQIndex];
 async function submitExam(){const current=examPhase==='mcq'?currentExamQuestion:currentExamCaseQuestion;if(!current||!answer)return;setBusy(true);setError('');try{const r=await api('/api/exam/grade',{method:'POST',body:JSON.stringify({question_id:current.id,selected:answer})});if(r.correct){setExamCorrect(x=>x+1);if(examPhase==='mcq')setExamMcqCorrect(x=>x+1)}setAnswer('');if(examPhase==='mcq'){if(examIndex+1<exam.mcq_questions.length){setExamIndex(examIndex+1)}else if(examMcqCorrect+Number(r.correct)>=50&&exam.cases.length){setExamPhase('cases');setExamCaseIndex(0);setExamCaseQIndex(0);setExamTotal(exam.mcq_questions.length+exam.cases.reduce((n,c)=>n+c.questions.length,0));setExamStartedAt(Math.floor(Date.now()/1000));setExamSecondsLeft(60*60)}else{setExamPhase('done');setExamTotal(exam.mcq_questions.length)}}else if(examCaseQIndex+1<currentExamCase.questions.length){setExamCaseQIndex(examCaseQIndex+1)}else if(examCaseIndex+1<exam.cases.length){setExamCaseIndex(examCaseIndex+1);setExamCaseQIndex(0)}else{setExamPhase('done')}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function loadTab(t){setTab(t);setError('');if(t==='Dashboard'){setDashboard(await api('/api/dashboard'))}if(t==='Study Plan'){setStudy(await api('/api/study-plan'))}}
 async function newSession(){const s=await api('/api/session/new',{method:'POST'});setSession(s.stats);setQ(null);writeLocal(QUESTION_KEY,null);setReview(null);setDrillCount(0)}
 async function saveSettings(next){const clean={part:next.part,difficulty:next.difficulty,domain:next.domain};setPrefs(clean);writeLocal(PREF_KEY,clean);setQ(null);writeLocal(QUESTION_KEY,null);setReview(null);setDrillCount(0);try{await api('/api/preferences',{method:'POST',body:JSON.stringify(clean)})}catch(e){setError('Settings saved on this device. Cloud sync is unavailable right now.')}}
 return <div className="app"><header><div className="eyebrow">ADAPTIVE CMA STUDY</div><h1>📘 CMA Coach</h1><p>Your personal CMA learning coach — practice, learn, and improve.</p></header><div className="layout"><aside><h3>Practice Settings</h3><label>CMA Part<select value={prefs.part} onChange={e=>saveSettings({...prefs,part:e.target.value,domain:'All'})}>{['Both','Part 1','Part 2'].map(x=><option key={x}>{x}</option>)}</select></label><label>Difficulty<select value={prefs.difficulty} onChange={e=>saveSettings({...prefs,difficulty:e.target.value})}>{['All','Easy','Medium','Hard'].map(x=><option key={x}>{x}</option>)}</select></label><label>Domain<select value={prefs.domain} onChange={e=>saveSettings({...prefs,domain:e.target.value})}><option>All</option>{domains.map(x=><option key={x}>{x}</option>)}</select></label><div className="side-note">✓ Settings saved on this device</div></aside><main><nav>{['Practice','Case Practice','Exam Simulation','Dashboard','Study Plan'].map(t=><button className={tab===t?'active':''} onClick={()=>loadTab(t)} key={t}>{t}</button>)}</nav>{error&&<div className="error">{error}</div>}{tab==='Practice'&&<Practice q={q} review={review} answer={answer} setAnswer={setAnswer} confidence={confidence} setConfidence={setConfidence} busy={busy} choose={choose} submit={submit} next={next} session={session} drillCount={drillCount}/>} {tab==='Case Practice'&&<CasePractice data={caseData} index={caseIndex} review={caseReview} answer={answer} setAnswer={setAnswer} confidence={confidence} setConfidence={setConfidence} busy={busy} start={startCase} submit={submitCase} next={nextCase}/>} {tab==='Exam Simulation'&&<ExamSimulation exam={exam} phase={examPhase} q={currentExamQuestion} c={currentExamCase} cq={currentExamCaseQuestion} index={examIndex} caseIndex={examCaseIndex} caseQIndex={examCaseQIndex} answer={answer} setAnswer={setAnswer} busy={busy} start={startExam} submit={submitExam} correct={examCorrect} mcqCorrect={examMcqCorrect} total={examTotal} secondsLeft={examSecondsLeft}/>} {tab==='Dashboard'&&<Dashboard data={dashboard} newSession={newSession} reviewDue={startDueReview}/>} {tab==='Study Plan'&&<Study data={study} refresh={()=>setStudy(null)}/>}</main></div></div>
}

function Practice({q,review,answer,setAnswer,confidence,setConfidence,busy,choose,submit,next,session,drillCount}){return <section><div className="section"><h2>Adaptive Practice</h2><p>The goal is to learn the concept behind the question, not just improve the score.</p></div><span className="pill">Session · {session.attempted} answered</span>{drillCount>0&&drillCount<3&&<span className="pill">Concept Drill · {drillCount+1}/3</span>}{drillCount===3&&<span className="pill">Concept Drill · Complete</span>}{!q?<div className="empty"><p>Choose your settings, then start a practice session.</p><button className="primary" disabled={busy} onClick={choose}>🎯 Start Practice</button></div>:<><div className="question"><div className="meta">{q.part} · {q.domain} · {q.difficulty}</div><div className="qtext">{q.question}</div></div>{!review?<AnswerBox q={q} answer={answer} setAnswer={setAnswer} confidence={confidence} setConfidence={setConfidence} submit={submit} busy={busy}/>:<CoachReview review={review} q={q} busy={busy} next={next} drillCount={drillCount}/>}</>}</section>}

function AnswerBox({q,answer,setAnswer,confidence,setConfidence,submit,busy,hideConfidence=false}){return <div className="answer"><h3>Your answer</h3>{Object.entries(q.choices).map(([k,v])=><label className={'choice '+(answer===k?'selected':'')} key={k}><input type="radio" name="answer" checked={answer===k} onChange={()=>setAnswer(k)}/><b>{k}.</b> {v}</label>)}{!hideConfidence&&<><h3>How sure are you?</h3><div className="confidence">{[[1,'🔴 Not sure'],[2,'🟡 Somewhat sure'],[3,'🟢 Very sure']].map(([v,t])=><button className={confidence===v?'selected':''} onClick={()=>setConfidence(v)} key={v}>{t}</button>)}</div></>}<button className="primary full" disabled={!answer||(!hideConfidence&&!confidence)||busy} onClick={submit}>{busy?'Checking…':'Submit Answer'}</button></div>}

function CoachReview({review,q,busy,next,drillCount}){const f=review.feedback||{};const answerText=q?.choices?.[f.correct_answer||q.answer]||'';const drillComplete=drillCount>=3;return <div className="coach"><div className="meta">🧠 COACH REVIEW</div>{drillCount>0&&<div className="meta">🎯 CONCEPT DRILL · {drillComplete?'Complete':'Question '+(drillCount+1)+' of 3'}</div>}{review.correct?<div className="success">Correct — make sure you know why.</div>:<div className="wrong">Incorrect. Correct answer: <b>{f.correct_answer||q.answer}</b>{answerText&&<> — {answerText}</>}</div>}<h3>{f.diagnosis}</h3><p>{f.advice}</p><h3>Why</h3><p>{f.explanation||'This question is testing the rule shown above.'}</p>{f.calculation&&<><h3>Calculation</h3><pre>{f.calculation}</pre></>}{drillComplete?<div className="card"><b>Concept check complete.</b><br/><span>You practiced this concept without jumping to another domain. Return to mixed practice when you're ready.</span></div>:<div className="actions"><button className="primary" disabled={busy} onClick={()=>next(true)}>🎯 Practice This Concept</button><button disabled={busy} onClick={()=>next(false)}>Next Mixed Question</button></div>}{drillComplete&&<div className="actions"><button className="primary" disabled={busy} onClick={()=>next(false)}>Next Mixed Question</button></div>}</div>}

function CasePractice({data,index,review,answer,setAnswer,confidence,setConfidence,busy,start,submit,next}){if(!data)return <section><div className="section"><h2>Case-Based Practice</h2><p>Practice the short business scenarios used by the current CMA exam format.</p></div><div className="empty"><p>Work through a complete case set one question at a time.</p><button className="primary" disabled={busy} onClick={start}>🧩 Start Case Practice</button></div></section>;const cq=data.questions[index];return <section><div className="section"><h2>{data.title}</h2><p>Case {data.id} · Question {index+1} of {data.questions.length}</p></div><div className="case-scenario"><div className="meta">BUSINESS SCENARIO · {data.domain}</div><div>{data.scenario}</div></div>{!review?<><div className="question"><div className="meta">Question {index+1}</div><div className="qtext">{cq.question}</div></div><AnswerBox q={cq} answer={answer} setAnswer={setAnswer} confidence={confidence} setConfidence={setConfidence} submit={submit} busy={busy}/></>:<CoachReview review={review} q={cq} busy={busy} next={()=>{}} drillCount={3}/>} {review&&<div className="actions"><button className="primary" disabled={busy} onClick={next}>{index+1<data.questions.length?'Next Case Question':'Finish Case & Start Another'}</button></div>}</section>}

function ExamSimulation({exam,phase,q,c,cq,index,caseIndex,caseQIndex,answer,setAnswer,busy,start,submit,correct,mcqCorrect,total,secondsLeft}){if(!exam)return <section><div className="section"><h2>Exam Simulation</h2><p>A full-length simulation using the current CMA structure: 100 multiple-choice questions followed by two case-based sets.</p></div><div className="card"><b>4-hour simulation</b><br/><span>3 hours for the 100 MCQs, then 1 hour for the two case-based sets. The case section requires at least 50% on the MCQ section. Answers stay hidden until the simulation ends.</span></div><div className="empty"><button className="primary" disabled={busy} onClick={start}>⏱ Start Exam Simulation</button></div></section>;if(phase==='done')return <section><div className="section"><h2>Simulation Complete</h2></div><div className="grid2"><Stat label="MCQ Correct" value={`${mcqCorrect}/100`}/><Stat label="Overall Correct" value={`${correct}/${total}`}/></div>{mcqCorrect<50?<div className="card"><b>MCQ gate not reached.</b><br/><span>You need at least 50% on the multiple-choice section to unlock the case-based section in the real exam format.</span></div>:<div className="card"><b>Simulation score: {total?Math.round(correct/total*100):0}%</b><br/><span>This is a practice diagnostic, not an estimate of an official scaled score.</span></div>}<button onClick={start}>↻ Start Another Simulation</button></section>;const mins=Math.floor(secondsLeft/60),secs=String(secondsLeft%60).padStart(2,'0'),current=phase==='mcq'?q:cq;return <section><div className="section"><h2>Exam Simulation · {exam.part}</h2><p>{phase==='mcq'?`Multiple choice · Question ${index+1} of ${exam.mcq_count}`:`Case-based section · Set ${caseIndex+1} of ${exam.cases.length} · Question ${caseQIndex+1} of ${c.questions.length}`}</p></div><div className="exam-bar"><span>⏱ {mins}:{secs}</span><span>MCQ correct: {mcqCorrect}/100</span></div>{phase==='cases'&&<div className="case-scenario"><div className="meta">BUSINESS SCENARIO · {c.domain}</div><div>{c.scenario}</div></div>}<div className="question"><div className="meta">{current.domain||c?.domain} · {current.difficulty||'Case-based'}</div><div className="qtext">{current.question}</div></div><AnswerBox q={current} answer={answer} setAnswer={setAnswer} submit={submit} busy={busy} hideConfidence/></section>}
function Stat({label,value}){return <div className="stat"><div>{label}</div><strong>{value}</strong></div>}
function Dashboard({data,newSession,reviewDue}){if(!data)return <div className="loading">Loading dashboard…</div>;const {stats:s,snapshot,adaptive={}}=data;const priorities=[...snapshot.weak_domains.map(x=>({domain:x,icon:'🔴',label:'Needs work',text:'Accuracy is below the current threshold. Prioritize this area.'})),...snapshot.fragile_domains.filter(x=>!snapshot.weak_domains.includes(x)).map(x=>({domain:x,icon:'🟡',label:'Reinforce',text:'You are getting these right, but confidence is still fragile.'}))];const mastery=adaptive.mastery_by_domain||s.mastery||[];return <section><div className="section"><h2>Historical Progress</h2></div><div className="grid2"><Stat label="Questions Completed" value={s.attempted}/><Stat label="Lifetime Accuracy" value={s.accuracy+'%'}/></div><button onClick={newSession}>↻ Start New Session Now</button><div className="section"><h2>Next Best Review</h2></div>{adaptive.due_count?<div className="card"><b>🔁 {adaptive.due_count} review{adaptive.due_count===1?'':'s'} due</b><br/><span>{adaptive.next_best_action?.reason||'A previous question is ready for retrieval.'}</span>{adaptive.next_best_action?.domain&&<><br/><span><b>Area:</b> {adaptive.next_best_action.domain}</span></>}<br/><button className="primary" onClick={reviewDue}>Start Due Review</button></div>:<p>No scheduled reviews are due right now. Keep practicing and the coach will schedule them based on your answers and confidence.</p>}<div className="section"><h2>What To Study Next</h2></div>{priorities.length?priorities.map(x=><div className="card" key={x.domain}>{x.icon} <b>{x.domain}</b><br/><span><b>{x.label}.</b> {x.text}</span></div>):<p>Keep practicing. The coach will identify priorities as your history grows.</p>}<div className="section"><h2>Mastery by Domain</h2></div>{mastery.map(r=><div className="mastery" key={r.domain}><b>{({New:'⚪',Learning:'🟡',Weak:'🔴',Mastered:'🟢'})[r.status]} {r.domain}</b><span>{r.status}</span></div>)}</section>}
function Study({data,refresh}){if(!data)return <div className="loading">Loading study plan…</div>;const g=data.goal,p=data.plan;return <section><div className="section"><h2>Current Study Plan</h2></div>{g&&<div className="info">📅 Exam target: <b>{g.target_date}</b> · <b>{g.part}</b> · <b>{g.daily_minutes} minutes/day</b></div>}<StudyForm refresh={refresh} g={g}/>{p.message?<p>Set your exam target and daily study time to generate a plan.</p>:<><div className="grid2"><Stat label="Days Remaining" value={p.days_remaining}/><Stat label="Daily Target" value={p.daily_minutes+' min'}/></div><div className="section"><h2>Focus Areas</h2></div>{p.focus_topics.map(x=><div className="card" key={x}>🎯 <b>{x}</b></div>)}<div className="section"><h2>Suggested Session</h2></div>{p.session.map(x=><p key={x}>• {x}</p>)}</>}</section>}
function StudyForm({g,refresh}){const [target,setTarget]=useState(g?.target_date||new Date().toISOString().slice(0,10)),[part,setPart]=useState(g?.part||'Part 1'),[mins,setMins]=useState(g?.daily_minutes||30);return <div className="goal"><label>Target exam date<input type="date" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Part<select value={part} onChange={e=>setPart(e.target.value)}>{['Part 1','Part 2','Both'].map(x=><option key={x}>{x}</option>)}</select></label><label>Daily study minutes<input type="number" min="10" max="240" value={mins} onChange={e=>setMins(e.target.value)}/></label><button className="primary" onClick={async()=>{await api('/api/study-plan',{method:'POST',body:JSON.stringify({target_date:target,part,daily_minutes:Number(mins)})});refresh()}}>Save Study Goal</button></div>}

createRoot(document.getElementById('root')).render(<App/>);