import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const p1=['External Financial Reporting Decisions','Planning, Budgeting, and Forecasting','Performance Management','Cost Management','Internal Controls','Technology and Analytics'];
const p2=['Financial Statement Analysis','Corporate Finance','Business Decision Analysis','Enterprise Risk Management','Capital Investment Decisions','Professional Ethics'];
const api=(path,opts={})=>fetch(path,{headers:{'Content-Type':'application/json'},...opts}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.detail||'Request failed');return d});

function App(){
 const [prefs,setPrefs]=useState({part:'Both',difficulty:'All',domain:'All'}),[q,setQ]=useState(null),[answer,setAnswer]=useState(''),[confidence,setConfidence]=useState(0),[review,setReview]=useState(null),[session,setSession]=useState({attempted:0,accuracy:0}),[tab,setTab]=useState('Practice'),[dashboard,setDashboard]=useState(null),[study,setStudy]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{Promise.all([api('/api/preferences'),api('/api/session')]).then(([p,s])=>{setPrefs(p);setSession(s.stats);if(p.resume_question_id)api('/api/question/'+p.resume_question_id).then(setQ).catch(()=>{});}).catch(e=>setError(e.message));},[]);
 const domains=prefs.part==='Part 1'?p1:prefs.part==='Part 2'?p2:[...p1,...p2];
 async function choose(){setBusy(true);setError('');try{const x=await api('/api/question',{method:'POST',body:JSON.stringify(prefs)});setQ(x);setReview(null);setAnswer('');setConfidence(0)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function submit(){if(!answer||!confidence)return;setBusy(true);try{const r=await api('/api/grade',{method:'POST',body:JSON.stringify({question_id:q.id,selected:answer,confidence})});setReview(r);setSession(r.session)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function next(follow=false){setBusy(true);try{const r=await api(follow?'/api/followup':'/api/question',{method:'POST',body:JSON.stringify(follow?{question_id:q.id,selected:answer,part:prefs.part,difficulty:prefs.difficulty}:{...prefs,exclude:[q.id]})});setQ(r);setReview(null);setAnswer('');setConfidence(0)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function loadTab(t){setTab(t);setError('');if(t==='Dashboard'&&!dashboard){setDashboard(await api('/api/dashboard'))}if(t==='Study Plan'&&!study){setStudy(await api('/api/study-plan'))}}
 async function newSession(){const s=await api('/api/session/new',{method:'POST'});setSession(s.stats);setQ(null);setReview(null)}
 async function saveSettings(next){setPrefs(next);setQ(null);setReview(null);await api('/api/preferences',{method:'POST',body:JSON.stringify(next)})}
 return <div className="app"><header><div className="eyebrow">ADAPTIVE CMA STUDY</div><h1>📘 CMA Coach</h1><p>Your personal CMA learning coach — practice, learn, and improve.</p></header><div className="layout"><aside><h3>Practice Settings</h3><label>CMA Part<select value={prefs.part} onChange={e=>saveSettings({...prefs,part:e.target.value,domain:'All'})}>{['Both','Part 1','Part 2'].map(x=><option key={x}>{x}</option>)}</select></label><label>Difficulty<select value={prefs.difficulty} onChange={e=>saveSettings({...prefs,difficulty:e.target.value})}>{['All','Easy','Medium','Hard'].map(x=><option key={x}>{x}</option>)}</select></label><label>Domain<select value={prefs.domain} onChange={e=>saveSettings({...prefs,domain:e.target.value})}><option>All</option>{domains.map(x=><option key={x}>{x}</option>)}</select></label><div className="side-note">✓ Settings saved automatically</div></aside><main><nav>{['Practice','Dashboard','Study Plan'].map(t=><button className={tab===t?'active':''} onClick={()=>loadTab(t)} key={t}>{t}</button>)}</nav>{error&&<div className="error">{error}</div>}{tab==='Practice'&&<Practice q={q} review={review} answer={answer} setAnswer={setAnswer} confidence={confidence} setConfidence={setConfidence} busy={busy} choose={choose} submit={submit} next={next} session={session}/>} {tab==='Dashboard'&&<Dashboard data={dashboard} newSession={newSession}/>} {tab==='Study Plan'&&<Study data={study} refresh={()=>setStudy(null)}/>}</main></div></div>
}

function Practice({q,review,answer,setAnswer,confidence,setConfidence,busy,choose,submit,next,session}){return <section><div className="section"><h2>Adaptive Practice</h2><p>The goal is to learn the concept behind the question, not just improve the score.</p></div><span className="pill">Session · {session.attempted} answered</span>{!q?<div className="empty"><p>Choose your settings, then start a practice session.</p><button className="primary" disabled={busy} onClick={choose}>🎯 Start Practice</button></div>:<><div className="question"><div className="meta">{q.part} · {q.domain} · {q.difficulty}</div><div className="qtext">{q.question}</div></div>{!review?<div className="answer"><h3>Your answer</h3>{Object.entries(q.choices).map(([k,v])=><label className={'choice '+(answer===k?'selected':'')} key={k}><input type="radio" name="answer" checked={answer===k} onChange={()=>setAnswer(k)}/><b>{k}.</b> {v}</label>)}<h3>How sure are you?</h3><div className="confidence">{[[1,'🔴 Not sure'],[2,'🟡 Somewhat sure'],[3,'🟢 Very sure']].map(([v,t])=><button className={confidence===v?'selected':''} onClick={()=>setConfidence(v)} key={v}>{t}</button>)}</div><button className="primary full" disabled={!answer||!confidence||busy} onClick={submit}>{busy?'Checking…':'Submit Answer'}</button></div>:<div className="coach"><div className="meta">🧠 COACH REVIEW</div>{review.correct?<div className="success">Correct — now make sure you know why.</div>:<div className="wrong">Incorrect. Correct answer: <b>{review.question.answer}</b></div>}<h3>{review.feedback.diagnosis}</h3><p>{review.feedback.advice}</p><h3>The concept</h3><p>{review.feedback.explanation}</p>{review.feedback.calculation&&<><h3>Calculation</h3><pre>{review.feedback.calculation}</pre></>}<div className="actions"><button className="primary" disabled={busy} onClick={()=>next(true)}>🎯 Practice This Concept</button><button disabled={busy} onClick={()=>next(false)}>Next Mixed Question</button></div></div>}</>}</section>}

function Dashboard({data,newSession}){if(!data)return <div className="loading">Loading dashboard…</div>;const {stats:s,snapshot}=data;return <section><div className="section"><h2>Current Session</h2></div><div className="grid2"><Stat label="Questions Completed" value={s.attempted}/><Stat label="Lifetime Accuracy" value={s.accuracy+'%'}/></div><button onClick={newSession}>↻ Start New Session Now</button><div className="section"><h2>What To Study Next</h2></div>{snapshot.weak_domains.length?snapshot.weak_domains.map(x=><div className="card" key={x}>🔴 <b>{x}</b><br/><span>Below your current learning threshold — prioritize this area.</span></div>):snapshot.fragile_domains.length?snapshot.fragile_domains.map(x=><div className="card" key={x}>🟡 <b>{x}</b><br/><span>You are getting these right, but confidence is still fragile.</span></div>):<p>Keep practicing. The coach will identify priorities as your history grows.</p>}<div className="section"><h2>Mastery by Domain</h2></div>{s.mastery.map(r=><div className="mastery" key={r.domain}><b>{({New:'⚪',Learning:'🟡',Weak:'🔴',Mastered:'🟢'})[r.status]} {r.domain}</b><span>{r.status}</span></div>)}</section>}
function Stat({label,value}){return <div className="stat"><div>{label}</div><strong>{value}</strong></div>}
function Study({data,refresh}){if(!data)return <div className="loading">Loading study plan…</div>;const g=data.goal,p=data.plan;return <section><div className="section"><h2>Current Study Plan</h2></div>{g&&<div className="info">📅 Exam target: <b>{g.target_date}</b> · <b>{g.part}</b> · <b>{g.daily_minutes} minutes/day</b></div>}<StudyForm refresh={refresh} g={g}/>{p.message?<p>Set your exam target and daily study time to generate a plan.</p>:<><div className="grid2"><Stat label="Days Remaining" value={p.days_remaining}/><Stat label="Daily Target" value={p.daily_minutes+' min'}/></div><div className="section"><h2>Focus Areas</h2></div>{p.focus_topics.map(x=><div className="card" key={x}>🎯 <b>{x}</b></div>)}<div className="section"><h2>Suggested Session</h2></div>{p.session.map(x=><p key={x}>• {x}</p>)}</>}</section>}
function StudyForm({g,refresh}){const [target,setTarget]=useState(g?.target_date||new Date().toISOString().slice(0,10)),[part,setPart]=useState(g?.part||'Part 1'),[mins,setMins]=useState(g?.daily_minutes||30);return <div className="goal"><label>Target exam date<input type="date" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Part<select value={part} onChange={e=>setPart(e.target.value)}>{['Part 1','Part 2','Both'].map(x=><option key={x}>{x}</option>)}</select></label><label>Daily study minutes<input type="number" min="10" max="240" value={mins} onChange={e=>setMins(e.target.value)}/></label><button className="primary" onClick={async()=>{await api('/api/study-plan',{method:'POST',body:JSON.stringify({target_date:target,part,daily_minutes:Number(mins)})});refresh()}}>Save Study Goal</button></div>}

createRoot(document.getElementById('root')).render(<App/>);
